-- vim.api.nvim_create_autocmd('LspAttach', {
--     group = vim.api.nvim_create_augroup('my.lsp', { clear = true }),
--     callback = function(args)
--         local client = assert(vim.lsp.get_client_by_id(args.data.client_id))
--         local bufnr = args.buf
--
--         if
--             not client:supports_method('textDocument/willSaveWaitUntil')
--             and client:supports_method('textDocument/formatting')
--         then
--             vim.api.nvim_create_autocmd('BufWritePre', {
--                 group = vim.api.nvim_create_augroup('my.lsp.format.' .. bufnr, { clear = true }),
--                 buffer = bufnr,
--                 callback = function()
--                     vim.lsp.buf.format({
--                         bufnr = bufnr,
--                         id = client.id,
--                         timeout_ms = 1000,
--                     })
--                 end,
--             })
--         end
--     end,
-- })
