set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

#Reload config file
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# View Pane Name
set -g pane-border-status top
set -g pane-border-format " [ ###P #T ] "

# Rename a Pane
bind u command-prompt -p "Set pane name to:" "select-pane -T '%%'"

# Turn mouse on
set -g mouse on
